Repository m-mrcr/twocents-be, pull requests merged in 2019-09, with the labels that each got.

#8 adds continuous integration and deployment through TravisCI
  .travis.yml
Labels: enhancement, good first issue

#9 initializes the database, including setting up packages & config file
  config/config.json
  models/index.js
  package-lock.json
  package.json
Labels: enhancement

#14 Story 1 -
  app.js
  migrations/20190904230305-create-location.js
  models/location.js
  package-lock.json
  package.json
  routes/api/v1/search.js
  seeders/20190904224455-location_seeds.js
  test/app.test.js
  test/locations.test.js
Labels: enhancement

#17 Story 4
  .gitignore
  app.js
  migrations/20190906204942-create-location.js
  models/location.js
  package-lock.json
  package.json
  routes/api/v1/recommendations.js
  routes/api/v1/search.js
  routes/api/v1/users/recommendations.js
  seeders/20190904224455-location_seeds.js
  test/locations.test.js
  test/search.test.js
Labels: enhancement

#18 adjusts how users route file is called and the dummy rec route
  app.js
  routes/api/v1/users.js
  routes/api/v1/users/recommendations.js
Labels: enhancement

#19 Add coordinates to location objects
  migrations/20190907230440-create-location.js
  models/location.js
  seeders/20190904224455-location_seeds.js
  test/search.test.js
Labels: bug

#21 Yelp to location serializer
  migrations/20190907230440-create-location.js
  migrations/20190909200415-create-user.js
  migrations/20190909213827-create-user-location.js
  models/location.js
  models/user.js
  models/userlocation.js
  routes/api/v1/recommendations.js
  routes/api/v1/search.js
  routes/api/v1/users.js
  routes/api/v1/users/recommendations.js
  seeders/20190908175325-user_seeds.js
  seeders/20190908195307-userLocation_seeds.js
  serializers/yelpToLocationSerializer.js
  test/helper/testCleanup.js
  test/search.test.js
  test/user.recommendations.test.js
  test/user.test.js
  test/yelpToLocationSerializer.test.js
Labels: enhancement

#22 Post to users
  models/user.js
  routes/api/v1/recommendations.js
  routes/api/v1/search.js
  routes/api/v1/users.js
  routes/api/v1/users/recommendations.js
  seeders/20190908175325-user_seeds.js
  seeders/20190908195307-userLocation_seeds.js
  test/user.recommendations.test.js
  test/user.test.js
Labels: enhancement

#23 User recommend post delete
  models/userlocation.js
  routes/api/v1/users/recommendations.js
  seeders/20190904224455-location_seeds.js
  seeders/20190908195307-userLocation_seeds.js
  test/search.test.js
  test/user.recommendations.test.js
Labels: enhancement
